### ISSUE TITLE
Retrieving recording after call

### ISSUE THREAD

**Issue by flodi** [eyeson-team/eyeson-php#11]
How can I retrieve a recording of the call after it ended? Thank you

**Comment by unused** [comment]
The most convenient way to download a recording is to setup a [webhook](https://eyeson-team.github.io/api/api-reference/#register-webhooks) in order to receive a message in your application as soon as the recording is available and [fetch the recording via API](https://eyeson-team.github.io/api/api-reference/#recording).
Note: You only have to register a single webhook for your application to receive all recording updates.

Please do not hesitate to leave a comment if you have any troubles with the setup.
