### ISSUE TITLE
Number of room participants via PHP SDK

### ISSUE THREAD

**Issue by unlabeledlife** [eyeson-team/eyeson-php#13]
Is there a way with the PHP SDK to find the number of participants in a room before adding an additional? Any example?

**Comment by unused** [comment]
In order to keep track on a meeting you have can setup a webhook (one is enough for all your rooms). Any updates on a running session are delivered on the endpoint provided by you. Therefor you see when a meeting has started and when participants join. This is the common way to setup a meeting history or inform users on a running meeting.
However as this happens asynchronously it does not represent the current state of a meeting. If you require the exact state, you have to create an additional control participant, and connect to the real time channels.
Let me know if you have any further questions on this, best wishes!

**Comment by unlabeledlife** [comment]
To be clear this is what I need right?
`$eyeson->addWebhook('https://my.application/hooks/recordings', 'recording_update');`
Is there docs that detail what info these endpoints output? Or do I have to just run them all.
user_update
document_update
recording_update
broadcast_update
room_update
team_update  
presentation_update

**Comment by unused** [comment]
You just need the define the specific updates you want to receive. The `room_update` will be fine in most cases, it also contains updates on recordings, participants, etc.
