### ISSUE TITLE
Eyeson can't detect browser through iframe

### ISSUE THREAD

**Issue by LK1one** [eyeson-team/eyeson-php#47]
Hey eyeson team,

I'm currently developing an application where we wan't to implement eyeson into a iframe. Here is part of my code:

$eventParticipant->room_link echos "https://app.eyeson.team/?mhoks1GRxBNwHEQYvjS8AmUg"

`<iframe src="{{ $eventParticipant->room_link }}" allowfullscreen allow="microphone https://app.eyeson.team; camera https://app.eyeson.team" style="width:800px; height:500px;" >
</iframe>`

The problem is that your application is not tracking the used browser. I always shows this page in the iframe: 

Oh, dear!
Please open the link below in one of the supported browsers.
Google Chrome (recommended)
Mozilla Firefox
Apple Safari (Version 11)
Microsoft Edge

Any idea how I can make it work so it detects my browser? Thanks

**Comment by opusonline** [comment]
Hi.

Please try to avoid using iFrame, since iFrames always come with their own issues due to browser security limitations. We suggest to build your own custom UI based on **eyeson-js** (see https://eyeson-team.github.io/js-docs/).

The error on the page indicates that one or more requirements in your browser are not fulfilled. Have you tried to open the link "https://app.eyeson.team/?mhoks1GRxBNwHEQYvjS8AmUg" (or whatever your current `$eventParticipant->room_link` is) on a full page instead of an iFrame to verify that your environment is working correctly?

For further testing you should use the **Quick test** tool (https://app.eyeson.team/quicktest/) as it can give you more hints. You can even try this in the iFrame to identify any issues. Additionally I recommend the following "allow" features in the iFrame.

```html
<iframe src="https://app.eyeson.team/quicktest/" allow="camera; microphone; fullscreen; speaker; display-capture; picture-in-picture; web-share; autoplay"></iframe>
```

Do not hesitate to leave a comment if you have further questions. Best wishes!
