### ISSUE TITLE
How to schedule or create a  parmanent meeting link for coming days ?

### ISSUE THREAD

**Issue by aryaashwani28** [eyeson-team/eyeson-php#60]
I want to schedule a meeting for any specific coming day of week. How can i create a permanent meeting link & send it to the other person? Current meeting link get expired after 2 minutes.
I am creating a solution for patient & doctors where patient can schedule meeting for upcoming days.

**Comment by opusonline** [comment]
Hi,
this needs to be done on your side!
Using the API, you can start a meeting that is intended to be used immediately (that's why a user name is required), so please only start a meeting when it is immediately used.
In order to create a permanent link, you could generate a random id, store it in your app, and send this with the link to your app to future participants as a permanent meeting link (e.g. https://my.awesome-app.com/meeting/abc123). When the time has come and a user clicks the link, your app can start a meeting using our API with that random id as a specific room id (abc123 in this example).
I hope that helps!
Please do not hesitate to open another issue or leave a comment if you have any further questions!
Best regards, Stefan
