### ISSUE TITLE
Hello Getting error when passing youtube rtmp in broadcast

### ISSUE THREAD

**Issue by alamgira** [eyeson-team/eyeson-php#72]
Hello, 
I am passing youtube rtmp url to broadcast call and i am getting an error

Request failed. The request has failed for an unhandled reason. If you expect an error feel free to create an issue for the project anytime.

broadcast call Request
    $api_key = EYESON_API_KEY;
    $stream_url = "rtmps://a.rtmps.youtube.com/live2/YOUTUBE_STREAM_KEY";
    $platform = "generic";
    $access_key = $data->access_key;
    $eyeson = new Eyeson($api_key);
    
    $broadcast = $eyeson->broadcast($access_key, $platform, $stream_url);

**Comment by opusonline** [comment]
Hi,
I don't know how the `$eyeson->broadcast` method looks like, because it's not implemented in eyeson-php. Can you share the code for a closer look?
What I can tell so far is that the error message might be shown as a result of a bad request (400) and the reason for this can be a missing parameter. Please make sure that `stream_url` is passed correctly as parameter (see https://eyeson-team.github.io/api/api-reference/#broadcast).
Best regards,
Stefan

**Comment by alamgira** [comment]
Hello. $eyeson->broadcast is from eyeson php library which is calling their broadcast. I am passing youtube rtmp url with stream key in the url. Url is fine since i tried with OBS studio and it works. Access key is the eyeson room key which is active. It works if i am not using yt rtmp but a generic rtmp such as mux

**Comment by opusonline** [comment]
Good news, we have fixed the issue with Youtube rtmps stream urls, so it will work now with your initial settings.
Can you confirm it's working for you? Thank you in advance.

**Comment by alamgira** [comment]
Hello @opusonline , it is working with original settings. Thank you. You can close this issue
